services:
  web:
    build: Mongo\.
    ports:
      - 81:5002
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE: WebApp
    networks:
      flask_mongo_network:
        ipv4_address: "192.168.10.20"
    depends_on:
      - mongodb_service

  mongodb_service:
    container_name: mongodb
    image: mongo:4.0.8
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongoVolume:/etc/mongo
    networks:
      flask_mongo_network:
        ipv4_address: "192.168.10.21"

networks:
  flask_mongo_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"